version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mcSet
      - POSTGRES_USER=mcSet
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  backend:
    build: backend
    command: sh -c "python backend/manage.py wait_for_db && python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - ALLOWED_HOSTS=node85731-compose.unicloud.pl,170.187.186.22,127.0.0.1,localhost
      - DB_HOST=db
      - DB_NAME=mcSet
      - DB_USER=mcSet
      - DB_PASS=mysecretpassword
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
